
Write a NumPy program to create an array of all even integers from 30 to 70.


In [2]:
import numpy as np

In [4]:
x = np.arange(30,71)
x[::2]


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

Question : Create a 3×3 numpy array of all True’s


In [5]:
y = np.full((3,3),True)
y


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Question : Extract all odd numbers from array
 input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 output: array([1, 3, 5, 7, 9])

In [21]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
odd_numbers = []

for i in arr:
    if i % 2 != 0: 
        odd_numbers.append(i)

odd_numbers_array = np.array(odd_numbers)

print(odd_numbers_array)


        

[1 3 5 7 9]


Question: Replace all odd numbers in arr with -1
 input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

for i in arr:
    if i % 2 != 0:  
        arr[i] = -1 

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Question: Get the common items between a and b

 Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
        b = np.array([7,2,10,2,7,4,9,4,9,8])

 Output: array([2, 4])
 

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_elements = []
for i in a:
    for j in b:
        if i == j:
            if i not in common_elements:
                common_elements.append(i)

common_elements_array = np.array(common_elements)

print(common_elements_array)


[2 4]
