 Create a numpy array with filling random values, and shape of array
 should be (12,5), and pass this array from a user-defined function, and
 function should be able to return average, minimum, maximum, and
 For e.g. consider this is last row [41,52,63,96,85],
 Output:
 Average -> 67.4 Minimum -> 41
 Maximum -> 96
 No. of evens -> 2

In [1]:
import numpy as np

In [16]:
a = np.arange(60).reshape(12,5)
def process_last_row(arr):
    last_row = arr[-1]
    # average
    average= sum(last_row)/len(last_row)

    # minimum
    minimum=last_row[0]
    for i in last_row:
        if minimum>i:
             minimum = i
    minimum = minimum

    #maximum
    max_element = last_row[0]
    
    for element in last_row:
        if element > max_element:
            max_element = element
            
    maximum = max_element

    # number of even
    count = 0
    for i in last_row:
        if i % 2 == 0:
            count = count + 1
    num_evens = count

    #returning all the values
    return average, minimum, maximum, num_evens

    # call the function
average, minimum, maximum, num_evens = process_last_row(a)

# Print the array and the results
print("Array:")
print(a)
print("\nResults:")
print(f"Average -> {average}")
print(f"Minimum -> {minimum}")
print(f"Maximum -> {maximum}")
print(f"No. of evens -> {num_evens}")









Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]

Results:
Average -> 57.0
Minimum -> 55
Maximum -> 59
No. of evens -> 2


Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]]
And apply slicing techniques to get reversed order elements of all the rows,
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]]

In [20]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
reverse = a2[::-1,::-1]
print(reverse)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
