Given an array a = np.array([10, 20, 30, 40, 50]) and
an index array i = np.array([0, 1, 3]), use fancy indexing
to extract elements and assign new values to them. 


In [2]:
import numpy as np

In [29]:
a = np.array([10,20,30,40,50])
i = np.array([0,1,3])
extracted_element = a[i]
print(extracted_element)

new = np.array([12,13,14])
a[i]= new
print(a)

[10 20 40]
[12 13 30 14 50]


Create a 4x4 matrix and compute the sum of all elements, the sum
of each column, and the sum of each row.


In [27]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)
total = np.sum(arr1)
print(total)
row_total = np.sum(arr1,axis = 1)
print(row_total)
column_total = np.sum(arr1,axis = 0)
print(column_total)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
136
[10 26 42 58]
[28 32 36 40]


In [21]:
arr = np.arange(0,60).reshape(3,4,5)
arr
sub_array = arr[1:3, -2:, -2:]
sub_array


array([[[33, 34],
        [38, 39]],

       [[53, 54],
        [58, 59]]])